apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-creation-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group-creation
  template:
    metadata:
      labels:
        app: group-creation
    spec:
      containers:
        - name: group-creation
          image: jsmainwaring/group-creation
---
apiVersion: v1
kind: Service
metadata:
  name: group-creation-load-bal
spec:
  type: LoadBalancer
  selector:
    app: group-creation
  ports:
    - protocol: TCP
      # Port on master node to hit from inside cluster to be directed to group-creation pods
      port: 4011
      # Port it's running on within port/container 
      targetPort: 8008
      # Port on master node to hit from outside cluster to be directed to group-creation pods
      nodePort: 32200